// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: cross/core/msgs.proto

package types

import (
	context "context"
	fmt "fmt"
	types "github.com/cosmos/cosmos-sdk/x/ibc/core/02-client/types"
	_ "github.com/gogo/protobuf/gogoproto"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type MsgInitiate struct {
	Sender         AccountAddress `protobuf:"bytes,1,opt,name=sender,proto3,casttype=AccountAddress" json:"sender,omitempty"`
	ChainId        string         `protobuf:"bytes,2,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	Nonce          uint64         `protobuf:"varint,3,opt,name=nonce,proto3" json:"nonce,omitempty"`
	CommitProtocol uint32         `protobuf:"varint,4,opt,name=commit_protocol,json=commitProtocol,proto3" json:"commit_protocol,omitempty"`
	// Timeout height relative to the current block height.
	// The timeout is disabled when set to 0.
	TimeoutHeight types.Height `protobuf:"bytes,5,opt,name=timeout_height,json=timeoutHeight,proto3" json:"timeout_height" yaml:"timeout_height"`
	// Timeout timestamp (in nanoseconds) relative to the current block timestamp.
	// The timeout is disabled when set to 0.
	TimeoutTimestamp     uint64                `protobuf:"varint,6,opt,name=timeout_timestamp,json=timeoutTimestamp,proto3" json:"timeout_timestamp,omitempty" yaml:"timeout_timestamp"`
	ContractTransactions []ContractTransaction `protobuf:"bytes,7,rep,name=contract_transactions,json=contractTransactions,proto3" json:"contract_transactions"`
}

func (m *MsgInitiate) Reset()         { *m = MsgInitiate{} }
func (m *MsgInitiate) String() string { return proto.CompactTextString(m) }
func (*MsgInitiate) ProtoMessage()    {}
func (*MsgInitiate) Descriptor() ([]byte, []int) {
	return fileDescriptor_73f0ea9ff29132cf, []int{0}
}
func (m *MsgInitiate) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgInitiate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgInitiate.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgInitiate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgInitiate.Merge(m, src)
}
func (m *MsgInitiate) XXX_Size() int {
	return m.Size()
}
func (m *MsgInitiate) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgInitiate.DiscardUnknown(m)
}

var xxx_messageInfo_MsgInitiate proto.InternalMessageInfo

// MsgInitiateResponse defines the Msg/Initiate response type.
type MsgInitiateResponse struct {
}

func (m *MsgInitiateResponse) Reset()         { *m = MsgInitiateResponse{} }
func (m *MsgInitiateResponse) String() string { return proto.CompactTextString(m) }
func (*MsgInitiateResponse) ProtoMessage()    {}
func (*MsgInitiateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_73f0ea9ff29132cf, []int{1}
}
func (m *MsgInitiateResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgInitiateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgInitiateResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgInitiateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgInitiateResponse.Merge(m, src)
}
func (m *MsgInitiateResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgInitiateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgInitiateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgInitiateResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*MsgInitiate)(nil), "cross.core.MsgInitiate")
	proto.RegisterType((*MsgInitiateResponse)(nil), "cross.core.MsgInitiateResponse")
}

func init() { proto.RegisterFile("cross/core/msgs.proto", fileDescriptor_73f0ea9ff29132cf) }

var fileDescriptor_73f0ea9ff29132cf = []byte{
	// 466 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x92, 0xc1, 0x6e, 0xd3, 0x30,
	0x18, 0xc7, 0x63, 0xda, 0x75, 0xc5, 0x65, 0x05, 0x4c, 0x0b, 0xa1, 0x82, 0x38, 0xca, 0x85, 0x68,
	0x87, 0x44, 0x2b, 0xb7, 0xdd, 0x16, 0x76, 0xa0, 0x42, 0x93, 0x50, 0xb4, 0xd3, 0x2e, 0xc5, 0x71,
	0xac, 0xd4, 0x52, 0x63, 0x57, 0xb1, 0x3b, 0xb1, 0x37, 0xe0, 0xc8, 0x23, 0xec, 0xc4, 0xb3, 0xec,
	0xb8, 0x23, 0xa7, 0x0a, 0xb5, 0x17, 0xce, 0x3b, 0x72, 0x42, 0x49, 0xdc, 0x2d, 0x15, 0xe2, 0x14,
	0xfb, 0xe7, 0xdf, 0xf7, 0xd9, 0xf1, 0xdf, 0x70, 0x48, 0x0b, 0xa9, 0x54, 0x48, 0x65, 0xc1, 0xc2,
	0x5c, 0x65, 0x2a, 0x58, 0x14, 0x52, 0x4b, 0x04, 0x2b, 0x1c, 0x94, 0x78, 0x34, 0xc8, 0x64, 0x26,
	0x2b, 0x1c, 0x96, 0xa3, 0xda, 0x18, 0x61, 0x9e, 0xd0, 0xba, 0x8c, 0xce, 0x39, 0x13, 0x3a, 0xbc,
	0x3c, 0x32, 0x23, 0x23, 0xbc, 0x6c, 0x74, 0xd6, 0x57, 0x0b, 0x66, 0x5a, 0x7b, 0x3f, 0x5a, 0xb0,
	0x77, 0xa6, 0xb2, 0x89, 0xe0, 0x9a, 0x13, 0xcd, 0xd0, 0x21, 0xec, 0x28, 0x26, 0x52, 0x56, 0xd8,
	0xc0, 0x05, 0xfe, 0x93, 0x08, 0xfd, 0x59, 0xe1, 0xfe, 0x09, 0xa5, 0x72, 0x29, 0xf4, 0x49, 0x9a,
	0x16, 0x4c, 0xa9, 0xd8, 0x18, 0xe8, 0x35, 0xec, 0xd2, 0x19, 0xe1, 0x62, 0xca, 0x53, 0xfb, 0x91,
	0x0b, 0xfc, 0xc7, 0xf1, 0x7e, 0x35, 0x9f, 0xa4, 0x68, 0x00, 0xf7, 0x84, 0x14, 0x94, 0xd9, 0x2d,
	0x17, 0xf8, 0xed, 0xb8, 0x9e, 0xa0, 0x77, 0xf0, 0x29, 0x95, 0x79, 0xce, 0xf5, 0xb4, 0xda, 0x9c,
	0xca, 0xb9, 0xdd, 0x76, 0x81, 0x7f, 0x10, 0xf7, 0x6b, 0xfc, 0xd9, 0x50, 0xf4, 0x05, 0xf6, 0x35,
	0xcf, 0x99, 0x5c, 0xea, 0xe9, 0x8c, 0xf1, 0x6c, 0xa6, 0xed, 0x3d, 0x17, 0xf8, 0xbd, 0xf1, 0x28,
	0xe0, 0x09, 0xad, 0xee, 0x21, 0x30, 0x7f, 0x77, 0x79, 0x14, 0x7c, 0xac, 0x8c, 0xe8, 0xed, 0xcd,
	0x0a, 0x5b, 0x77, 0x2b, 0x3c, 0xbc, 0x22, 0xf9, 0xfc, 0xd8, 0xdb, 0xad, 0xf7, 0xe2, 0x03, 0x03,
	0x6a, 0x1b, 0x4d, 0xe0, 0xf3, 0xad, 0x51, 0x7e, 0x95, 0x26, 0xf9, 0xc2, 0xee, 0x94, 0x87, 0x8d,
	0xde, 0xdc, 0xad, 0xb0, 0xbd, 0xdb, 0xe4, 0x5e, 0xf1, 0xe2, 0x67, 0x86, 0x9d, 0x6f, 0x11, 0xba,
	0x80, 0x43, 0x2a, 0x85, 0x2e, 0x08, 0xd5, 0x53, 0x5d, 0x10, 0xa1, 0x08, 0xd5, 0x5c, 0x0a, 0x65,
	0xef, 0xbb, 0x2d, 0xbf, 0x37, 0xc6, 0xc1, 0x43, 0x7a, 0xc1, 0x07, 0x23, 0x9e, 0x3f, 0x78, 0x51,
	0xbb, 0x3c, 0x78, 0x3c, 0xa0, 0xff, 0x2e, 0xa9, 0xe3, 0xee, 0xb7, 0x6b, 0x6c, 0xfd, 0xbe, 0xc6,
	0x96, 0x37, 0x84, 0x2f, 0x1a, 0x39, 0xc5, 0x4c, 0x2d, 0xa4, 0x50, 0x6c, 0xfc, 0x09, 0xb6, 0xce,
	0x54, 0x86, 0x4e, 0x61, 0xf7, 0x3e, 0xc2, 0x57, 0xcd, 0x0d, 0x1b, 0x35, 0x23, 0xfc, 0x9f, 0x85,
	0x6d, 0xb3, 0xe8, 0xf4, 0x66, 0xed, 0x80, 0xdb, 0xb5, 0x03, 0x7e, 0xad, 0x1d, 0xf0, 0x7d, 0xe3,
	0x58, 0xb7, 0x1b, 0xc7, 0xfa, 0xb9, 0x71, 0xac, 0x8b, 0xc3, 0x8c, 0xeb, 0xd9, 0x32, 0x09, 0xa8,
	0xcc, 0xc3, 0x94, 0x68, 0x52, 0xe5, 0x3c, 0x27, 0x49, 0x58, 0x3f, 0xab, 0xaf, 0x8d, 0x87, 0x95,
	0x74, 0xaa, 0x70, 0xdf, 0xff, 0x0d, 0x00, 0x00, 0xff, 0xff, 0xd9, 0x3a, 0xb7, 0x17, 0xcd, 0x02,
	0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	// Initiate defines a rpc handler method for MsgInitiate.
	Initiate(ctx context.Context, in *MsgInitiate, opts ...grpc.CallOption) (*MsgInitiateResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) Initiate(ctx context.Context, in *MsgInitiate, opts ...grpc.CallOption) (*MsgInitiateResponse, error) {
	out := new(MsgInitiateResponse)
	err := c.cc.Invoke(ctx, "/cross.core.Msg/Initiate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	// Initiate defines a rpc handler method for MsgInitiate.
	Initiate(context.Context, *MsgInitiate) (*MsgInitiateResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) Initiate(ctx context.Context, req *MsgInitiate) (*MsgInitiateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Initiate not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_Initiate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgInitiate)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).Initiate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cross.core.Msg/Initiate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).Initiate(ctx, req.(*MsgInitiate))
	}
	return interceptor(ctx, in, info, handler)
}

var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "cross.core.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Initiate",
			Handler:    _Msg_Initiate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "cross/core/msgs.proto",
}

func (m *MsgInitiate) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgInitiate) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgInitiate) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.ContractTransactions) > 0 {
		for iNdEx := len(m.ContractTransactions) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.ContractTransactions[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintMsgs(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x3a
		}
	}
	if m.TimeoutTimestamp != 0 {
		i = encodeVarintMsgs(dAtA, i, uint64(m.TimeoutTimestamp))
		i--
		dAtA[i] = 0x30
	}
	{
		size, err := m.TimeoutHeight.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintMsgs(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x2a
	if m.CommitProtocol != 0 {
		i = encodeVarintMsgs(dAtA, i, uint64(m.CommitProtocol))
		i--
		dAtA[i] = 0x20
	}
	if m.Nonce != 0 {
		i = encodeVarintMsgs(dAtA, i, uint64(m.Nonce))
		i--
		dAtA[i] = 0x18
	}
	if len(m.ChainId) > 0 {
		i -= len(m.ChainId)
		copy(dAtA[i:], m.ChainId)
		i = encodeVarintMsgs(dAtA, i, uint64(len(m.ChainId)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Sender) > 0 {
		i -= len(m.Sender)
		copy(dAtA[i:], m.Sender)
		i = encodeVarintMsgs(dAtA, i, uint64(len(m.Sender)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgInitiateResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgInitiateResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgInitiateResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func encodeVarintMsgs(dAtA []byte, offset int, v uint64) int {
	offset -= sovMsgs(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgInitiate) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Sender)
	if l > 0 {
		n += 1 + l + sovMsgs(uint64(l))
	}
	l = len(m.ChainId)
	if l > 0 {
		n += 1 + l + sovMsgs(uint64(l))
	}
	if m.Nonce != 0 {
		n += 1 + sovMsgs(uint64(m.Nonce))
	}
	if m.CommitProtocol != 0 {
		n += 1 + sovMsgs(uint64(m.CommitProtocol))
	}
	l = m.TimeoutHeight.Size()
	n += 1 + l + sovMsgs(uint64(l))
	if m.TimeoutTimestamp != 0 {
		n += 1 + sovMsgs(uint64(m.TimeoutTimestamp))
	}
	if len(m.ContractTransactions) > 0 {
		for _, e := range m.ContractTransactions {
			l = e.Size()
			n += 1 + l + sovMsgs(uint64(l))
		}
	}
	return n
}

func (m *MsgInitiateResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func sovMsgs(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozMsgs(x uint64) (n int) {
	return sovMsgs(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgInitiate) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMsgs
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgInitiate: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgInitiate: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Sender", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsgs
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthMsgs
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthMsgs
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Sender = append(m.Sender[:0], dAtA[iNdEx:postIndex]...)
			if m.Sender == nil {
				m.Sender = []byte{}
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ChainId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsgs
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMsgs
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMsgs
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ChainId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Nonce", wireType)
			}
			m.Nonce = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsgs
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Nonce |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CommitProtocol", wireType)
			}
			m.CommitProtocol = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsgs
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CommitProtocol |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TimeoutHeight", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsgs
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMsgs
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthMsgs
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.TimeoutHeight.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TimeoutTimestamp", wireType)
			}
			m.TimeoutTimestamp = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsgs
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TimeoutTimestamp |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ContractTransactions", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsgs
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMsgs
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthMsgs
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ContractTransactions = append(m.ContractTransactions, ContractTransaction{})
			if err := m.ContractTransactions[len(m.ContractTransactions)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipMsgs(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthMsgs
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthMsgs
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgInitiateResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMsgs
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgInitiateResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgInitiateResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipMsgs(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthMsgs
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthMsgs
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipMsgs(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowMsgs
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowMsgs
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowMsgs
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthMsgs
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupMsgs
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthMsgs
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthMsgs        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowMsgs          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupMsgs = fmt.Errorf("proto: unexpected end of group")
)
