#!/bin/bash
set -e

NODE_DATA="$(pwd)/data"

NODE_NAME=simappcli
NODED_NAME=simappd

NODE_CLI=$(pwd)/../build/${NODE_NAME}
NODED_CLI=$(pwd)/../build/${NODED_NAME}

chainid0=ibc0
chainid1=ibc1
chainid2=ibc2

echo "Generating gaia configurations..."
mkdir -p $NODE_DATA && cd $NODE_DATA
echo -e "\n" | ${NODED_CLI} testnet -o $chainid0 --v 1 --chain-id $chainid0 --node-dir-prefix n --keyring-backend test &> /dev/null
echo -e "\n" | ${NODED_CLI} testnet -o $chainid1 --v 1 --chain-id $chainid1 --node-dir-prefix n --keyring-backend test &> /dev/null
echo -e "\n" | ${NODED_CLI} testnet -o $chainid2 --v 1 --chain-id $chainid2 --node-dir-prefix n --keyring-backend test &> /dev/null

cfgpth="n0/${NODED_NAME}/config/config.toml"
if [ "$(uname)" = "Linux" ]; then
  # TODO: Just index *some* specified tags, not all
  # sed -i 's/index_keys = ""/index_keys = "tx.height,tx.hash"'
  
  # Set proper defaults and change ports
  sed -i 's/"leveldb"/"goleveldb"/g' $chainid0/$cfgpth
  sed -i 's/"leveldb"/"goleveldb"/g' $chainid1/$cfgpth
  sed -i 's/"leveldb"/"goleveldb"/g' $chainid2/$cfgpth
  sed -i 's#"tcp://0.0.0.0:26656"#"tcp://0.0.0.0:26556"#g' $chainid1/$cfgpth
  sed -i 's#"tcp://0.0.0.0:26657"#"tcp://0.0.0.0:26557"#g' $chainid1/$cfgpth
  sed -i 's#"tcp://0.0.0.0:26656"#"tcp://0.0.0.0:26456"#g' $chainid2/$cfgpth
  sed -i 's#"tcp://0.0.0.0:26657"#"tcp://0.0.0.0:26457"#g' $chainid2/$cfgpth
  sed -i 's#"localhost:6060"#"localhost:6061"#g' $chainid1/$cfgpth
  sed -i 's#"localhost:6060"#"localhost:6062"#g' $chainid2/$cfgpth
  sed -i 's#"tcp://127.0.0.1:26658"#"tcp://127.0.0.1:26558"#g' $chainid1/$cfgpth
  sed -i 's#"tcp://127.0.0.1:26658"#"tcp://127.0.0.1:26458"#g' $chainid2/$cfgpth
  
  # Make blocks run faster than normal
  sed -i 's/timeout_commit = "5s"/timeout_commit = "1s"/g' $chainid0/$cfgpth
  sed -i 's/timeout_commit = "5s"/timeout_commit = "1s"/g' $chainid1/$cfgpth
  sed -i 's/timeout_commit = "5s"/timeout_commit = "1s"/g' $chainid2/$cfgpth
  sed -i 's/timeout_propose = "3s"/timeout_propose = "1s"/g' $chainid0/$cfgpth
  sed -i 's/timeout_propose = "3s"/timeout_propose = "1s"/g' $chainid1/$cfgpth
  sed -i 's/timeout_propose = "3s"/timeout_propose = "1s"/g' $chainid2/$cfgpth
else
  # TODO: Just index *some* specified tags, not all
  # sed -i 's/index_keys = ""/index_keys = "tx.height,tx.hash"'

  # Set proper defaults and change ports
  sed -i '' 's/"leveldb"/"goleveldb"/g' $chainid0/$cfgpth
  sed -i '' 's/"leveldb"/"goleveldb"/g' $chainid1/$cfgpth
  sed -i '' 's/"leveldb"/"goleveldb"/g' $chainid2/$cfgpth
  sed -i '' 's#"tcp://0.0.0.0:26656"#"tcp://0.0.0.0:26556"#g' $chainid1/$cfgpth
  sed -i '' 's#"tcp://0.0.0.0:26657"#"tcp://0.0.0.0:26557"#g' $chainid1/$cfgpth
  sed -i '' 's#"tcp://0.0.0.0:26656"#"tcp://0.0.0.0:26456"#g' $chainid2/$cfgpth
  sed -i '' 's#"tcp://0.0.0.0:26657"#"tcp://0.0.0.0:26457"#g' $chainid2/$cfgpth
  sed -i '' 's#"localhost:6060"#"localhost:6061"#g' $chainid1/$cfgpth
  sed -i '' 's#"localhost:6060"#"localhost:6062"#g' $chainid2/$cfgpth
  sed -i '' 's#"tcp://127.0.0.1:26658"#"tcp://127.0.0.1:26558"#g' $chainid1/$cfgpth
  sed -i '' 's#"tcp://127.0.0.1:26658"#"tcp://127.0.0.1:26458"#g' $chainid2/$cfgpth

  # Make blocks run faster than normal
  sed -i '' 's/timeout_commit = "5s"/timeout_commit = "1s"/g' $chainid0/$cfgpth
  sed -i '' 's/timeout_commit = "5s"/timeout_commit = "1s"/g' $chainid1/$cfgpth
  sed -i '' 's/timeout_commit = "5s"/timeout_commit = "1s"/g' $chainid2/$cfgpth
  sed -i '' 's/timeout_propose = "3s"/timeout_propose = "1s"/g' $chainid0/$cfgpth
  sed -i '' 's/timeout_propose = "3s"/timeout_propose = "1s"/g' $chainid1/$cfgpth
  sed -i '' 's/timeout_propose = "3s"/timeout_propose = "1s"/g' $chainid2/$cfgpth
fi

gclpth="n0/${NODE_NAME}/"
${NODE_CLI} config --home $chainid0/$gclpth chain-id $chainid0 &> /dev/null
${NODE_CLI} config --home $chainid1/$gclpth chain-id $chainid1 &> /dev/null
${NODE_CLI} config --home $chainid2/$gclpth chain-id $chainid2 &> /dev/null
${NODE_CLI} config --home $chainid0/$gclpth output json &> /dev/null
${NODE_CLI} config --home $chainid1/$gclpth output json &> /dev/null
${NODE_CLI} config --home $chainid2/$gclpth output json &> /dev/null
${NODE_CLI} config --home $chainid0/$gclpth node http://localhost:26657 &> /dev/null
${NODE_CLI} config --home $chainid1/$gclpth node http://localhost:26557 &> /dev/null
${NODE_CLI} config --home $chainid2/$gclpth node http://localhost:26457 &> /dev/null

echo "Starting ${NODED_NAME} instances..."
${NODED_CLI} --home $NODE_DATA/$chainid0/n0/${NODED_NAME} start --pruning=nothing > $chainid0.log 2>&1 &
${NODED_CLI} --home $NODE_DATA/$chainid1/n0/${NODED_NAME} start --pruning=nothing > $chainid1.log 2>&1 & 
${NODED_CLI} --home $NODE_DATA/$chainid2/n0/${NODED_NAME} start --pruning=nothing > $chainid2.log 2>&1 & 
