// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: cross/atomic/simple/types.proto

package types

import (
	fmt "fmt"
	github_com_datachainlab_cross_x_core_types "github.com/datachainlab/cross/x/core/types"
	types "github.com/datachainlab/cross/x/core/types"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type PacketDataCall struct {
	Sender github_com_datachainlab_cross_x_core_types.AccountAddress `protobuf:"bytes,1,opt,name=sender,proto3,casttype=github.com/datachainlab/cross/x/core/types.AccountAddress" json:"sender,omitempty"`
	TxId   github_com_datachainlab_cross_x_core_types.TxID           `protobuf:"bytes,2,opt,name=tx_id,json=txId,proto3,casttype=github.com/datachainlab/cross/x/core/types.TxID" json:"tx_id,omitempty"`
	TxInfo types.ContractTransactionInfo                             `protobuf:"bytes,3,opt,name=tx_info,json=txInfo,proto3" json:"tx_info"`
}

func (m *PacketDataCall) Reset()         { *m = PacketDataCall{} }
func (m *PacketDataCall) String() string { return proto.CompactTextString(m) }
func (*PacketDataCall) ProtoMessage()    {}
func (*PacketDataCall) Descriptor() ([]byte, []int) {
	return fileDescriptor_3027e825f7ea6c51, []int{0}
}
func (m *PacketDataCall) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *PacketDataCall) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_PacketDataCall.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *PacketDataCall) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PacketDataCall.Merge(m, src)
}
func (m *PacketDataCall) XXX_Size() int {
	return m.Size()
}
func (m *PacketDataCall) XXX_DiscardUnknown() {
	xxx_messageInfo_PacketDataCall.DiscardUnknown(m)
}

var xxx_messageInfo_PacketDataCall proto.InternalMessageInfo

func (m *PacketDataCall) GetSender() github_com_datachainlab_cross_x_core_types.AccountAddress {
	if m != nil {
		return m.Sender
	}
	return nil
}

func (m *PacketDataCall) GetTxId() github_com_datachainlab_cross_x_core_types.TxID {
	if m != nil {
		return m.TxId
	}
	return nil
}

func (m *PacketDataCall) GetTxInfo() types.ContractTransactionInfo {
	if m != nil {
		return m.TxInfo
	}
	return types.ContractTransactionInfo{}
}

func init() {
	proto.RegisterType((*PacketDataCall)(nil), "cross.atomic.simple.PacketDataCall")
}

func init() { proto.RegisterFile("cross/atomic/simple/types.proto", fileDescriptor_3027e825f7ea6c51) }

var fileDescriptor_3027e825f7ea6c51 = []byte{
	// 302 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0xd1, 0xbf, 0x4b, 0x03, 0x31,
	0x14, 0xc0, 0xf1, 0x8b, 0xd6, 0x0a, 0xa7, 0x38, 0x9c, 0x22, 0xa5, 0xc3, 0x5d, 0xd1, 0xa5, 0xd3,
	0x05, 0xec, 0xe4, 0xe0, 0xd0, 0x1f, 0x83, 0x1d, 0x04, 0x29, 0x75, 0x71, 0x91, 0xd7, 0x24, 0x6d,
	0x83, 0xd7, 0xbc, 0x92, 0xbc, 0xc2, 0xf9, 0x5f, 0xf8, 0x67, 0x75, 0xec, 0xe8, 0x54, 0xa4, 0xfd,
	0x1b, 0x5c, 0x3a, 0xc9, 0x5d, 0x1c, 0x14, 0x04, 0x71, 0x4b, 0xc8, 0x97, 0x0f, 0xe1, 0xbd, 0x30,
	0x11, 0x16, 0x9d, 0xe3, 0x40, 0x38, 0xd3, 0x82, 0x3b, 0x3d, 0x9b, 0x67, 0x8a, 0xd3, 0xcb, 0x5c,
	0xb9, 0x74, 0x6e, 0x91, 0x30, 0x3a, 0x2d, 0x83, 0xd4, 0x07, 0xa9, 0x0f, 0xea, 0x67, 0x13, 0x9c,
	0x60, 0xf9, 0xce, 0x8b, 0x93, 0x4f, 0xeb, 0xe7, 0xde, 0x12, 0x68, 0x7f, 0x10, 0x17, 0x1f, 0x2c,
	0x3c, 0xb9, 0x07, 0xf1, 0xac, 0xa8, 0x07, 0x04, 0x5d, 0xc8, 0xb2, 0xe8, 0x21, 0xac, 0x3a, 0x65,
	0xa4, 0xb2, 0x35, 0xd6, 0x60, 0xcd, 0xe3, 0xce, 0xcd, 0x6e, 0x9d, 0x5c, 0x4f, 0x34, 0x4d, 0x17,
	0xa3, 0x54, 0xe0, 0x8c, 0x4b, 0x20, 0x10, 0x53, 0xd0, 0x26, 0x83, 0x11, 0xf7, 0x6c, 0xfe, 0x1d,
	0x6e, 0x0b, 0x81, 0x0b, 0x43, 0x6d, 0x29, 0xad, 0x72, 0x6e, 0xf0, 0x85, 0x45, 0xb7, 0xe1, 0x01,
	0xe5, 0x4f, 0x5a, 0xd6, 0xf6, 0x4a, 0xb5, 0xb5, 0x5b, 0x27, 0xfc, 0x1f, 0xea, 0x30, 0xef, 0xf7,
	0x06, 0x15, 0xca, 0xfb, 0x32, 0xea, 0x84, 0x87, 0x85, 0x64, 0xc6, 0x58, 0xdb, 0x6f, 0xb0, 0xe6,
	0xd1, 0xd5, 0x65, 0xea, 0x07, 0x51, 0xe4, 0x69, 0x17, 0x0d, 0x59, 0x10, 0x34, 0xb4, 0x60, 0x1c,
	0x08, 0xd2, 0x68, 0xfa, 0x66, 0x8c, 0x9d, 0xca, 0x72, 0x9d, 0x04, 0x83, 0x2a, 0xe5, 0xe5, 0xed,
	0x6e, 0xb9, 0x89, 0xd9, 0x6a, 0x13, 0xb3, 0xf7, 0x4d, 0xcc, 0x5e, 0xb7, 0x71, 0xb0, 0xda, 0xc6,
	0xc1, 0xdb, 0x36, 0x0e, 0x1e, 0x5b, 0x7f, 0x7d, 0xea, 0x97, 0x7d, 0x8c, 0xaa, 0xe5, 0x34, 0x5b,
	0x9f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x08, 0x32, 0xde, 0x63, 0xb3, 0x01, 0x00, 0x00,
}

func (m *PacketDataCall) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *PacketDataCall) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *PacketDataCall) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.TxInfo.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintTypes(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	if len(m.TxId) > 0 {
		i -= len(m.TxId)
		copy(dAtA[i:], m.TxId)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.TxId)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Sender) > 0 {
		i -= len(m.Sender)
		copy(dAtA[i:], m.Sender)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.Sender)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintTypes(dAtA []byte, offset int, v uint64) int {
	offset -= sovTypes(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *PacketDataCall) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Sender)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	l = len(m.TxId)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	l = m.TxInfo.Size()
	n += 1 + l + sovTypes(uint64(l))
	return n
}

func sovTypes(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTypes(x uint64) (n int) {
	return sovTypes(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *PacketDataCall) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: PacketDataCall: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: PacketDataCall: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Sender", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Sender = append(m.Sender[:0], dAtA[iNdEx:postIndex]...)
			if m.Sender == nil {
				m.Sender = []byte{}
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TxId", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TxId = append(m.TxId[:0], dAtA[iNdEx:postIndex]...)
			if m.TxId == nil {
				m.TxId = []byte{}
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TxInfo", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.TxInfo.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTypes(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthTypes
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthTypes
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTypes(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTypes
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTypes
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTypes
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTypes        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTypes          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTypes = fmt.Errorf("proto: unexpected end of group")
)
