// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: cross/atomic/common/types.proto

package types

import (
	fmt "fmt"
	github_com_datachainlab_cross_x_core_types "github.com/datachainlab/cross/x/core/types"
	types "github.com/datachainlab/cross/x/core/types"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type CoordinatorPhase int32

const (
	COORDINATOR_PHASE_NONE    CoordinatorPhase = 0
	COORDINATOR_PHASE_PREPARE CoordinatorPhase = 1
	COORDINATOR_PHASE_COMMIT  CoordinatorPhase = 2
)

var CoordinatorPhase_name = map[int32]string{
	0: "COORDINATOR_PHASE_NONE",
	1: "COORDINATOR_PHASE_PREPARE",
	2: "COORDINATOR_PHASE_COMMIT",
}

var CoordinatorPhase_value = map[string]int32{
	"COORDINATOR_PHASE_NONE":    0,
	"COORDINATOR_PHASE_PREPARE": 1,
	"COORDINATOR_PHASE_COMMIT":  2,
}

func (x CoordinatorPhase) String() string {
	return proto.EnumName(CoordinatorPhase_name, int32(x))
}

func (CoordinatorPhase) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_460c7def86bc66cc, []int{0}
}

type CoordinatorDecision int32

const (
	CoordinatorDecision_COORDINATOR_DECISION_NONE   CoordinatorDecision = 0
	CoordinatorDecision_COORDINATOR_DECISION_COMMIT CoordinatorDecision = 1
	CoordinatorDecision_COORDINATOR_DECISION_ABORT  CoordinatorDecision = 2
)

var CoordinatorDecision_name = map[int32]string{
	0: "COORDINATOR_DECISION_NONE",
	1: "COORDINATOR_DECISION_COMMIT",
	2: "COORDINATOR_DECISION_ABORT",
}

var CoordinatorDecision_value = map[string]int32{
	"COORDINATOR_DECISION_NONE":   0,
	"COORDINATOR_DECISION_COMMIT": 1,
	"COORDINATOR_DECISION_ABORT":  2,
}

func (x CoordinatorDecision) String() string {
	return proto.EnumName(CoordinatorDecision_name, int32(x))
}

func (CoordinatorDecision) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_460c7def86bc66cc, []int{1}
}

type CoordinatorState struct {
	Channels     []types.ChannelInfo                                     `protobuf:"bytes,1,rep,name=channels,proto3" json:"channels"`
	Phase        CoordinatorPhase                                        `protobuf:"varint,2,opt,name=phase,proto3,enum=cross.atomic.common.CoordinatorPhase" json:"phase,omitempty"`
	Decision     CoordinatorDecision                                     `protobuf:"varint,3,opt,name=decision,proto3,enum=cross.atomic.common.CoordinatorDecision" json:"decision,omitempty"`
	ConfirmedTxs github_com_datachainlab_cross_x_core_types.TxIndexSlice `protobuf:"bytes,4,opt,name=confirmed_txs,json=confirmedTxs,proto3,casttype=github.com/datachainlab/cross/x/core/types.TxIndexSlice" json:"confirmed_txs,omitempty"`
	Acks         github_com_datachainlab_cross_x_core_types.TxIndexSlice `protobuf:"bytes,5,opt,name=acks,proto3,casttype=github.com/datachainlab/cross/x/core/types.TxIndexSlice" json:"acks,omitempty"`
}

func (m *CoordinatorState) Reset()         { *m = CoordinatorState{} }
func (m *CoordinatorState) String() string { return proto.CompactTextString(m) }
func (*CoordinatorState) ProtoMessage()    {}
func (*CoordinatorState) Descriptor() ([]byte, []int) {
	return fileDescriptor_460c7def86bc66cc, []int{0}
}
func (m *CoordinatorState) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *CoordinatorState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_CoordinatorState.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *CoordinatorState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CoordinatorState.Merge(m, src)
}
func (m *CoordinatorState) XXX_Size() int {
	return m.Size()
}
func (m *CoordinatorState) XXX_DiscardUnknown() {
	xxx_messageInfo_CoordinatorState.DiscardUnknown(m)
}

var xxx_messageInfo_CoordinatorState proto.InternalMessageInfo

func init() {
	proto.RegisterEnum("cross.atomic.common.CoordinatorPhase", CoordinatorPhase_name, CoordinatorPhase_value)
	proto.RegisterEnum("cross.atomic.common.CoordinatorDecision", CoordinatorDecision_name, CoordinatorDecision_value)
	proto.RegisterType((*CoordinatorState)(nil), "cross.atomic.common.CoordinatorState")
}

func init() { proto.RegisterFile("cross/atomic/common/types.proto", fileDescriptor_460c7def86bc66cc) }

var fileDescriptor_460c7def86bc66cc = []byte{
	// 455 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x93, 0xc1, 0x8a, 0xd3, 0x40,
	0x1c, 0xc6, 0x93, 0xb6, 0x2b, 0x65, 0x5c, 0x25, 0xcc, 0xca, 0x1a, 0xa3, 0x26, 0x45, 0x10, 0xca,
	0x1e, 0x12, 0xd8, 0x3d, 0x88, 0xee, 0xa9, 0x4d, 0x03, 0xe6, 0xd0, 0xa6, 0x4c, 0x73, 0xf2, 0x52,
	0xa7, 0x93, 0xd9, 0x36, 0xd8, 0xce, 0xd4, 0xcc, 0x2c, 0xc4, 0x37, 0xd8, 0x8b, 0xe0, 0x23, 0x2c,
	0xf8, 0x32, 0x7b, 0xdc, 0xa3, 0xa7, 0x45, 0xda, 0x8b, 0xcf, 0xe0, 0x49, 0x92, 0x59, 0x4b, 0x75,
	0x03, 0x3d, 0xec, 0xad, 0xf0, 0xfd, 0xbe, 0xdf, 0xbf, 0x7c, 0x49, 0x80, 0x43, 0x32, 0x2e, 0x84,
	0x87, 0x25, 0x5f, 0xa4, 0xc4, 0x23, 0x7c, 0xb1, 0xe0, 0xcc, 0x93, 0x5f, 0x96, 0x54, 0xb8, 0xcb,
	0x8c, 0x4b, 0x0e, 0x0f, 0x4a, 0xc0, 0x55, 0x80, 0xab, 0x00, 0xeb, 0xc9, 0x94, 0x4f, 0x79, 0x99,
	0x7b, 0xc5, 0x2f, 0x85, 0x5a, 0x87, 0xca, 0x45, 0x78, 0x46, 0xb7, 0x15, 0xaf, 0xbe, 0xd6, 0x81,
	0xe1, 0x73, 0x9e, 0x25, 0x29, 0xc3, 0x92, 0x67, 0x23, 0x89, 0x25, 0x85, 0x6f, 0x41, 0x93, 0xcc,
	0x30, 0x63, 0x74, 0x2e, 0x4c, 0xbd, 0x55, 0x6f, 0x3f, 0x3c, 0x7e, 0xea, 0xaa, 0x53, 0x45, 0xdf,
	0xf5, 0x55, 0x16, 0xb2, 0x33, 0xde, 0x6d, 0x5c, 0xdd, 0x38, 0x1a, 0xda, 0xe0, 0xf0, 0x14, 0xec,
	0x2d, 0x67, 0x58, 0x50, 0xb3, 0xd6, 0xd2, 0xdb, 0x8f, 0x8f, 0x5f, 0xbb, 0x15, 0x7f, 0xd1, 0xdd,
	0x3a, 0x38, 0x2c, 0x60, 0xa4, 0x3a, 0xb0, 0x07, 0x9a, 0x09, 0x25, 0xa9, 0x48, 0x39, 0x33, 0xeb,
	0x65, 0xbf, 0xbd, 0xab, 0xdf, 0xbb, 0xe5, 0xd1, 0xa6, 0x09, 0x3f, 0x82, 0x47, 0x84, 0xb3, 0xb3,
	0x34, 0x5b, 0xd0, 0x64, 0x2c, 0x73, 0x61, 0x36, 0x5a, 0x7a, 0x7b, 0xbf, 0x7b, 0xfa, 0xfb, 0xc6,
	0x79, 0x33, 0x4d, 0xe5, 0xec, 0x7c, 0x52, 0x78, 0xbc, 0x04, 0x4b, 0x4c, 0x66, 0x38, 0x65, 0x73,
	0x3c, 0xf1, 0xd4, 0x3a, 0xf9, 0xf6, 0x3e, 0x71, 0x1e, 0xb2, 0x84, 0xe6, 0xa3, 0x79, 0x4a, 0x28,
	0xda, 0xdf, 0x18, 0xe3, 0x5c, 0xc0, 0x08, 0x34, 0x30, 0xf9, 0x24, 0xcc, 0xbd, 0xfb, 0x8b, 0x4b,
	0xd1, 0xbb, 0xe6, 0xc5, 0xa5, 0xa3, 0xfd, 0xba, 0x74, 0xb4, 0xa3, 0xcf, 0xff, 0x3c, 0x8e, 0x72,
	0x1d, 0x68, 0x81, 0x43, 0x3f, 0x8a, 0x50, 0x2f, 0x1c, 0x74, 0xe2, 0x08, 0x8d, 0x87, 0xef, 0x3b,
	0xa3, 0x60, 0x3c, 0x88, 0x06, 0x81, 0xa1, 0xc1, 0x97, 0xe0, 0xd9, 0xdd, 0x6c, 0x88, 0x82, 0x61,
	0x07, 0x05, 0x86, 0x0e, 0x5f, 0x00, 0xf3, 0x6e, 0xec, 0x47, 0xfd, 0x7e, 0x18, 0x1b, 0x35, 0xab,
	0x71, 0xf1, 0xdd, 0xd6, 0x8e, 0xce, 0xc1, 0x41, 0xc5, 0xa0, 0xff, 0x9b, 0x7b, 0x81, 0x1f, 0x8e,
	0xc2, 0x68, 0xf0, 0xf7, 0xb0, 0x03, 0x9e, 0x57, 0xc6, 0xb7, 0x72, 0x1d, 0xda, 0xc0, 0xaa, 0x04,
	0x3a, 0xdd, 0x08, 0xc5, 0x46, 0xad, 0xdb, 0xbf, 0x5a, 0xd9, 0xfa, 0xf5, 0xca, 0xd6, 0x7f, 0xae,
	0x6c, 0xfd, 0xdb, 0xda, 0xd6, 0xae, 0xd7, 0xb6, 0xf6, 0x63, 0x6d, 0x6b, 0x1f, 0x4e, 0x76, 0x8d,
	0x59, 0xf1, 0x45, 0x4c, 0x1e, 0x94, 0xef, 0xf3, 0xc9, 0x9f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xca,
	0x98, 0xb9, 0x48, 0x35, 0x03, 0x00, 0x00,
}

func (m *CoordinatorState) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *CoordinatorState) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *CoordinatorState) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Acks) > 0 {
		i -= len(m.Acks)
		copy(dAtA[i:], m.Acks)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.Acks)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.ConfirmedTxs) > 0 {
		i -= len(m.ConfirmedTxs)
		copy(dAtA[i:], m.ConfirmedTxs)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.ConfirmedTxs)))
		i--
		dAtA[i] = 0x22
	}
	if m.Decision != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.Decision))
		i--
		dAtA[i] = 0x18
	}
	if m.Phase != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.Phase))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Channels) > 0 {
		for iNdEx := len(m.Channels) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Channels[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintTypes(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintTypes(dAtA []byte, offset int, v uint64) int {
	offset -= sovTypes(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *CoordinatorState) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Channels) > 0 {
		for _, e := range m.Channels {
			l = e.Size()
			n += 1 + l + sovTypes(uint64(l))
		}
	}
	if m.Phase != 0 {
		n += 1 + sovTypes(uint64(m.Phase))
	}
	if m.Decision != 0 {
		n += 1 + sovTypes(uint64(m.Decision))
	}
	l = len(m.ConfirmedTxs)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	l = len(m.Acks)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	return n
}

func sovTypes(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTypes(x uint64) (n int) {
	return sovTypes(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *CoordinatorState) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: CoordinatorState: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: CoordinatorState: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Channels", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Channels = append(m.Channels, types.ChannelInfo{})
			if err := m.Channels[len(m.Channels)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Phase", wireType)
			}
			m.Phase = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Phase |= CoordinatorPhase(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Decision", wireType)
			}
			m.Decision = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Decision |= CoordinatorDecision(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ConfirmedTxs", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ConfirmedTxs = append(m.ConfirmedTxs[:0], dAtA[iNdEx:postIndex]...)
			if m.ConfirmedTxs == nil {
				m.ConfirmedTxs = []byte{}
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Acks", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Acks = append(m.Acks[:0], dAtA[iNdEx:postIndex]...)
			if m.Acks == nil {
				m.Acks = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTypes(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthTypes
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthTypes
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTypes(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTypes
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTypes
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTypes
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTypes        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTypes          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTypes = fmt.Errorf("proto: unexpected end of group")
)
