// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: cross/atomic/simple/types.proto

package types

import (
	fmt "fmt"
	github_com_datachainlab_cross_x_tx_types "github.com/datachainlab/cross/x/tx/types"
	types "github.com/datachainlab/cross/x/tx/types"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type CommitStatus int32

const (
	COMMIT_STATUS_UNKNOWN CommitStatus = 0
	COMMIT_STATUS_OK      CommitStatus = 1
	COMMIT_STATUS_FAILED  CommitStatus = 2
)

var CommitStatus_name = map[int32]string{
	0: "COMMIT_STATUS_UNKNOWN",
	1: "COMMIT_STATUS_OK",
	2: "COMMIT_STATUS_FAILED",
}

var CommitStatus_value = map[string]int32{
	"COMMIT_STATUS_UNKNOWN": 0,
	"COMMIT_STATUS_OK":      1,
	"COMMIT_STATUS_FAILED":  2,
}

func (x CommitStatus) String() string {
	return proto.EnumName(CommitStatus_name, int32(x))
}

func (CommitStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_3027e825f7ea6c51, []int{0}
}

type PacketDataCall struct {
	TxId github_com_datachainlab_cross_x_tx_types.TxID `protobuf:"bytes,1,opt,name=tx_id,json=txId,proto3,casttype=github.com/datachainlab/cross/x/tx/types.TxID" json:"tx_id,omitempty"`
	Tx   types.ResolvedContractTransaction             `protobuf:"bytes,2,opt,name=tx,proto3" json:"tx"`
}

func (m *PacketDataCall) Reset()         { *m = PacketDataCall{} }
func (m *PacketDataCall) String() string { return proto.CompactTextString(m) }
func (*PacketDataCall) ProtoMessage()    {}
func (*PacketDataCall) Descriptor() ([]byte, []int) {
	return fileDescriptor_3027e825f7ea6c51, []int{0}
}
func (m *PacketDataCall) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *PacketDataCall) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_PacketDataCall.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *PacketDataCall) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PacketDataCall.Merge(m, src)
}
func (m *PacketDataCall) XXX_Size() int {
	return m.Size()
}
func (m *PacketDataCall) XXX_DiscardUnknown() {
	xxx_messageInfo_PacketDataCall.DiscardUnknown(m)
}

var xxx_messageInfo_PacketDataCall proto.InternalMessageInfo

type PacketAcknowledgementCall struct {
	Status CommitStatus `protobuf:"varint,1,opt,name=status,proto3,enum=cross.atomic.simple.CommitStatus" json:"status,omitempty"`
}

func (m *PacketAcknowledgementCall) Reset()         { *m = PacketAcknowledgementCall{} }
func (m *PacketAcknowledgementCall) String() string { return proto.CompactTextString(m) }
func (*PacketAcknowledgementCall) ProtoMessage()    {}
func (*PacketAcknowledgementCall) Descriptor() ([]byte, []int) {
	return fileDescriptor_3027e825f7ea6c51, []int{1}
}
func (m *PacketAcknowledgementCall) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *PacketAcknowledgementCall) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_PacketAcknowledgementCall.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *PacketAcknowledgementCall) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PacketAcknowledgementCall.Merge(m, src)
}
func (m *PacketAcknowledgementCall) XXX_Size() int {
	return m.Size()
}
func (m *PacketAcknowledgementCall) XXX_DiscardUnknown() {
	xxx_messageInfo_PacketAcknowledgementCall.DiscardUnknown(m)
}

var xxx_messageInfo_PacketAcknowledgementCall proto.InternalMessageInfo

func init() {
	proto.RegisterEnum("cross.atomic.simple.CommitStatus", CommitStatus_name, CommitStatus_value)
	proto.RegisterType((*PacketDataCall)(nil), "cross.atomic.simple.PacketDataCall")
	proto.RegisterType((*PacketAcknowledgementCall)(nil), "cross.atomic.simple.PacketAcknowledgementCall")
}

func init() { proto.RegisterFile("cross/atomic/simple/types.proto", fileDescriptor_3027e825f7ea6c51) }

var fileDescriptor_3027e825f7ea6c51 = []byte{
	// 401 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x91, 0x4f, 0x6b, 0xd4, 0x40,
	0x18, 0xc6, 0x67, 0x96, 0xb5, 0x87, 0xb1, 0x94, 0x10, 0x23, 0x6c, 0xf7, 0x30, 0xa9, 0x05, 0xa1,
	0x08, 0x4e, 0xb0, 0x9e, 0xfc, 0x73, 0xd9, 0xcd, 0x5a, 0x08, 0xb5, 0xbb, 0x92, 0x4d, 0x11, 0x8a,
	0x10, 0x66, 0x27, 0x43, 0x1a, 0x9a, 0x64, 0x96, 0xcc, 0x5b, 0x1d, 0xbf, 0x81, 0x47, 0xef, 0x5e,
	0x04, 0xbf, 0xcc, 0x1e, 0x7b, 0xf4, 0x54, 0x74, 0xf7, 0xe2, 0x67, 0xf0, 0x24, 0x66, 0x0a, 0xee,
	0x82, 0xd0, 0xdb, 0xf0, 0xbe, 0xbf, 0xf9, 0xf1, 0xf0, 0x3e, 0xc4, 0x17, 0x8d, 0xd2, 0x3a, 0xe0,
	0xa0, 0xaa, 0x42, 0x04, 0xba, 0xa8, 0xe6, 0xa5, 0x0c, 0xe0, 0xe3, 0x5c, 0x6a, 0x36, 0x6f, 0x14,
	0x28, 0xf7, 0x5e, 0x0b, 0x30, 0x0b, 0x30, 0x0b, 0xf4, 0xbd, 0x5c, 0xe5, 0xaa, 0xdd, 0x07, 0x7f,
	0x5f, 0x16, 0xed, 0x7b, 0xd6, 0x05, 0x66, 0x5d, 0xb0, 0xff, 0x05, 0x93, 0x9d, 0x37, 0x5c, 0x5c,
	0x48, 0x18, 0x71, 0xe0, 0x21, 0x2f, 0x4b, 0xf7, 0x88, 0xdc, 0x01, 0x93, 0x16, 0x59, 0x0f, 0xef,
	0xe1, 0x83, 0xed, 0xe1, 0x93, 0xdf, 0xd7, 0xfe, 0xe3, 0xbc, 0x80, 0xf3, 0xcb, 0x19, 0x13, 0xaa,
	0x0a, 0x32, 0x0e, 0x5c, 0x9c, 0xf3, 0xa2, 0x2e, 0xf9, 0x2c, 0xb0, 0x4e, 0xf3, 0xcf, 0x9a, 0x98,
	0x68, 0x14, 0x77, 0xc1, 0x44, 0x99, 0xfb, 0x82, 0x74, 0xc0, 0xf4, 0x3a, 0x7b, 0xf8, 0xe0, 0xee,
	0xe1, 0x43, 0x66, 0x83, 0x82, 0x61, 0xb1, 0xd4, 0xaa, 0x7c, 0x2f, 0xb3, 0x50, 0xd5, 0xd0, 0x70,
	0x01, 0x49, 0xc3, 0x6b, 0xcd, 0x05, 0x14, 0xaa, 0x1e, 0x76, 0x17, 0xd7, 0x3e, 0x8a, 0x3b, 0x60,
	0x9e, 0x77, 0x7f, 0x7d, 0xf5, 0xd1, 0xfe, 0x3b, 0xb2, 0x6b, 0xc3, 0x0d, 0xc4, 0x45, 0xad, 0x3e,
	0x94, 0x32, 0xcb, 0x65, 0x25, 0x6b, 0x68, 0x73, 0x3e, 0x23, 0x5b, 0x1a, 0x38, 0x5c, 0xea, 0x36,
	0xe8, 0xce, 0xe1, 0x03, 0xf6, 0x9f, 0x63, 0xb0, 0x50, 0x55, 0x55, 0x01, 0xd3, 0x16, 0x8c, 0x6f,
	0x3e, 0x58, 0xfb, 0xa3, 0x94, 0x6c, 0xaf, 0x6f, 0xdd, 0x5d, 0x72, 0x3f, 0x9c, 0x9c, 0x9c, 0x44,
	0x49, 0x3a, 0x4d, 0x06, 0xc9, 0xe9, 0x34, 0x3d, 0x1d, 0x1f, 0x8f, 0x27, 0x6f, 0xc7, 0x0e, 0x72,
	0x3d, 0xe2, 0x6c, 0xae, 0x26, 0xc7, 0x0e, 0x76, 0x7b, 0xc4, 0xdb, 0x9c, 0x1e, 0x0d, 0xa2, 0xd7,
	0xaf, 0x46, 0x4e, 0xa7, 0xdf, 0xfd, 0xf4, 0x8d, 0xa2, 0xe1, 0xd9, 0xe2, 0x27, 0x45, 0x8b, 0x25,
	0xc5, 0x57, 0x4b, 0x8a, 0x7f, 0x2c, 0x29, 0xfe, 0xbc, 0xa2, 0xe8, 0x6a, 0x45, 0xd1, 0xf7, 0x15,
	0x45, 0x67, 0x2f, 0x6f, 0x3b, 0xea, 0x4d, 0xed, 0x6d, 0x51, 0x42, 0x95, 0x1b, 0xfd, 0xcf, 0xb6,
	0xda, 0xf1, 0xd3, 0x3f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x94, 0xb1, 0xad, 0x7a, 0x23, 0x02, 0x00,
	0x00,
}

func (m *PacketDataCall) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *PacketDataCall) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *PacketDataCall) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Tx.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintTypes(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	if len(m.TxId) > 0 {
		i -= len(m.TxId)
		copy(dAtA[i:], m.TxId)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.TxId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *PacketAcknowledgementCall) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *PacketAcknowledgementCall) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *PacketAcknowledgementCall) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Status != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.Status))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintTypes(dAtA []byte, offset int, v uint64) int {
	offset -= sovTypes(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *PacketDataCall) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.TxId)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	l = m.Tx.Size()
	n += 1 + l + sovTypes(uint64(l))
	return n
}

func (m *PacketAcknowledgementCall) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Status != 0 {
		n += 1 + sovTypes(uint64(m.Status))
	}
	return n
}

func sovTypes(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTypes(x uint64) (n int) {
	return sovTypes(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *PacketDataCall) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: PacketDataCall: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: PacketDataCall: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TxId", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TxId = append(m.TxId[:0], dAtA[iNdEx:postIndex]...)
			if m.TxId == nil {
				m.TxId = []byte{}
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Tx", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Tx.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTypes(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthTypes
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthTypes
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *PacketAcknowledgementCall) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: PacketAcknowledgementCall: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: PacketAcknowledgementCall: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
			}
			m.Status = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Status |= CommitStatus(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTypes(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthTypes
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthTypes
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTypes(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTypes
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTypes
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTypes
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTypes        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTypes          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTypes = fmt.Errorf("proto: unexpected end of group")
)
