#!/bin/bash
set -eux

PREV_DIR=$(pwd)
RELAYER_DIR=$(mktemp -d)
RLY_REVISION=3b6c36aa5056567dd244966d9100413831391d63

echo "RELAYER_DIR is ${RELAYER_DIR}"

cd ${RELAYER_DIR}
git clone https://github.com/hyperledger-labs/yui-relayer
cd ./yui-relayer
git checkout ${RLY_REVISION}
echo "Building Relayer..."
make build
mv ./build/uly ${PREV_DIR}/bin/rly
