#!/bin/bash
set -eux

PREV_DIR=$(pwd)
RELAYER_DIR=$(mktemp -d)
RLY_REVISION=c081e5287587c0c166f1a75b7ebc6845b79a8c8e

echo "RELAYER_DIR is ${RELAYER_DIR}"

cd ${RELAYER_DIR}
git clone https://github.com/hyperledger-labs/yui-relayer
cd ./yui-relayer
git checkout ${RLY_REVISION}
echo "Building Relayer..."
make build
mv ./build/uly ${PREV_DIR}/bin/rly
