#!/bin/bash
set -eux

PREV_DIR=$(pwd)
RELAYER_DIR=$(mktemp -d)
RLY_REVISION=6d0e3f45b4484c7502709548b9690a07a592a655

echo "RELAYER_DIR is ${RELAYER_DIR}"

cd ${RELAYER_DIR}
git clone https://github.com/hyperledger-labs/yui-relayer
cd ./yui-relayer
git checkout ${RLY_REVISION}
echo "Building Relayer..."
make build
mv ./build/uly ${PREV_DIR}/bin/rly
