#!/bin/bash

set -eux

source $(cd $(dirname "$0"); pwd)/util

RLY_BINARY=./bin/rly
RLY="${RLY_BINARY} --debug"

CHAINID_ONE=ibc0
RLYKEY=testkey
CHAINID_TWO=ibc1
PATH_NAME=ibc01

$RLY keys show $CHAINID_ONE $RLYKEY
$RLY keys show $CHAINID_TWO $RLYKEY

# configure the chain to use that key by default
$RLY ch edit $CHAINID_ONE key $RLYKEY
$RLY ch edit $CHAINID_TWO key $RLYKEY

# initialize the light client for {{chain_id}}
$RLY light init $CHAINID_ONE -f
$RLY light init $CHAINID_TWO -f

# you should see a balance for the rly key now
$RLY q bal $CHAINID_ONE
$RLY q bal $CHAINID_TWO

# either manually add a path by following the prompts...
$RLY paths gen $CHAINID_ONE $CHAINID_TWO $PATH_NAME \
--force \
--unordered \
--port cross \
--version cross-1 \
--strategy naive

retry 5 "$RLY tx clients $PATH_NAME"
retry 5 "$RLY tx connection $PATH_NAME"
retry 5 "$RLY tx channel $PATH_NAME"
