#!/bin/bash

set -eux

source $(cd $(dirname "$0"); pwd)/util

RLY_BINARY=./bin/rly
RLY="${RLY_BINARY} --debug"

CHAINID_ONE=ibc0
RLYKEY=testkey
CHAINID_TWO=ibc1
PATH_NAME=ibc01

$RLY tendermint keys show $CHAINID_ONE $RLYKEY
$RLY tendermint keys show $CHAINID_TWO $RLYKEY

# configure the chain to use that key by default
$RLY chains edit $CHAINID_ONE key $RLYKEY
$RLY chains edit $CHAINID_TWO key $RLYKEY

# initialize the light client for {{chain_id}}
retry 5 $RLY tendermint light init $CHAINID_ONE -f
retry 5 $RLY tendermint light init $CHAINID_TWO -f

# add a path between chain0 and chain1
$RLY paths add $CHAINID_ONE $CHAINID_TWO $PATH_NAME --file=./configs/path.json

retry 5 $RLY tx clients $PATH_NAME
retry 5 $RLY tx connection $PATH_NAME
retry 5 $RLY tx channel $PATH_NAME
