#!/bin/bash

set -eux

source $(cd $(dirname "$0"); pwd)/util

CHAIN_BINARY=../build/simd
RLY_BINARY=./bin/rly
RLY="${RLY_BINARY} --debug"

# initiator: chain0
# participant: chain1
CHAIN_0_HOME=./data/ibc-0
CHAIN_1_HOME=./data/ibc-1
CHAIN_0_CMD="${CHAIN_BINARY} --home ${CHAIN_0_HOME} --node tcp://localhost:26657"
CHAIN_1_CMD="${CHAIN_BINARY} --home ${CHAIN_1_HOME} --node tcp://localhost:26557"
KEY_OPT="--keyring-backend=test"

initiator_cc=$(${CHAIN_1_CMD} query ibc channel channels -o json | jq -r '.channels[0] | .channel_id + ":" + .port_id')

# Create a contract transaction of chain1 (no broadcast)
${CHAIN_1_CMD} query cross create-contract-tx \
    --call-info="{\"method\":\"counter\"}" \
    --signers=user \
    --initiator-chain-channel=${initiator_cc} \
    -o json \
    --output-document=./data/ibc-1-tx \
    ${KEY_OPT}

# Create a contract transaction of chain0 (no broadcast)
${CHAIN_0_CMD} query cross create-contract-tx \
    --call-info="{\"method\":\"counter\"}" \
    --signers=user \
    --initiator-chain=true \
    -o json \
    --output-document=./data/ibc-0-tx \
    ${KEY_OPT}

# Initiate a cross-chain transaction on chain0
res0=$(${CHAIN_0_CMD} tx cross initiate-tx \
    --from=user \
    --yes \
    --chain-id=ibc-0 \
    --contract-txs="./data/ibc-0-tx,./data/ibc-1-tx" \
    ${KEY_OPT})
echo $res0
tx_id=$(echo $res0 | jq -r '.data')

# Sign a cross-chain transaction on chain0 from chain1
${CHAIN_1_CMD} tx cross ibc-signtx \
    --from=user \
    --yes \
    --chain-id=ibc-1 \
    --tx-id=${tx_id} \
    --initiator-chain-channel=${initiator_cc} \
    ${KEY_OPT}

# TODO relay a packet
